stages:
  - build

  # https://github.com/gradle/gradle
.build:
  stage: build
  script: gradlew jpackage
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - build/jpackage/

build-jar:
  image: eclipse-temurin:17.0.7_7-jdk-alpine
  stage: build
  script:
    - ./gradlew clean build
  artifacts:
    name: "jar"
    paths:
      # tar, zip
      - build/distributions/
      # main jar
      - build/libs/
      - build/reports/
      - build/test-results/
    reports:
      junit: build/test-results/**/*.xml
    cache:
      paths:
        - build/
      policy: push
    
build-mac:
  extends: .build
  tags:
    - saas-macos-medium-m1
  script:
    - ./gradlew jpackage
    
#  image: macos-12-xcode-14
