# https://github.com/gradle/gradle

image: gradle:alpine

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

jpackage:
  stage: jpackage
  script: gradle jpackage
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
  artifacts:
  name: "$CI_JOB_NAME"
  paths:
    - build/jpackage/
