# https://github.com/gradle/gradle
.macos_saas_runners:
  tags:
    - saas-macos-medium-m1
  image: macos-12-xcode-14

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

stages:
  - build

build:
  stage: build
  extends:
    - .macos_saas_runners
  script: gradlew jpackage
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - build/jpackage/
