stages:
  - build
  
  # https://github.com/gradle/gradle
.build:
  stage: build
  script: gradlew jpackage
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - build/jpackage/

#before_script:
#  - GRADLE_USER_HOME="$(pwd)/.gradle"
#  - export GRADLE_USER_HOME

java-build:
  image: gradle:latest
  stage: build
  script:
    - ./gradlew jpackage
    
build-mac:
  extends: .build
  tags:
    - saas-macos-medium-m1
#  image: macos-12-xcode-14
