baseURL = 'https://nlcode.nl/'
languageCode = 'en-us'
title = 'm.nlcode.nl'
theme = "hugo-theme-relearn"
enableRobotsTXT = true

[outputs]
home = ["HTML", "RSS", "PRINT", "SEARCH"]
section = ["HTML", "RSS", "PRINT"]
page = ["HTML", "RSS", "PRINT"]

[module]
[[module.imports]]
  path = "github.com/McShelby/hugo-theme-relearn.git"

[params]
  themeVariant = ["relearn-dark", "red" ]